/** Shared list-analysis facade and deterministic source occurrence identities. */
import type * as t from '../ast/compiler-types';
import {walkAst, type BaseNode} from '../ast';
export {matchMapCall} from './source-shapes';
import type {Ctx, MapCallExpression} from '../context';
import {planListSite, type ListSitePlan} from './site-plan';
import {captureListSiteInputs} from '../planning/list-sites';

interface ErrorPath {
  buildCodeFrameError(message: string, at?: t.Node): Error;
}
interface NodeHolder {
  node: BaseNode;
}
type RuntimeBindingPattern =
  | t.Identifier
  | t.ObjectPattern
  | t.ArrayPattern;
export type ParentRow = Pick<
  MapSite,
  'itemParam' | 'sourceKey' | 'sourceLocal'
>;

export interface MapSite {
  /** Synchronous callback expressions replayed before the row DOM work. */
  prelude: t.ExpressionStatement[];
  /** Reactive source key (e.g. 'items' or 'store.todos'). */
  sourceKey: string;
  /** Ordered source expression, cloned into the reconcile calls. */
  sourceExpr: t.Expression;
  /** Optional-chain maps render no rows while their source is nullish. */
  optional: boolean;
  /** Instance roots invalidate their owner directly, not an access table. */
  sourceLocal: boolean;
  /** Runtime callback target, including supported destructuring patterns. */
  itemPattern: RuntimeBindingPattern;
  /** Representative item binding used by row mutation analysis. */
  itemParam: string;
  /** Optional callback index param name. */
  indexParam: string | null;
  /** Key expression if key={...} was given, else null. */
  keyExpr: t.Expression | null;
  /** The key merges spread attributes; nullish falls back to item identity. */
  keyFromSpread: boolean;
  /** Explicit index identity with no destructuring, prelude or key reads. */
  positional: boolean;
  /** Row JSX element, absent for a delegated render callback. */
  jsx: t.JSXElement | null;
  /** Component/host JSX or a caller-owned delegated row factory. */
  form: 'component' | 'inline' | 'callback';
  /** Component name when form === 'component'. */
  rowComp: string | null;
  /** Callback prop invoked when form === 'callback'. */
  renderCallback: t.Expression | null;
  /** Owning component name. */
  owner: string;
  /** Source key or source key plus a source-order occurrence suffix. */
  suffix: string;
  /** Unique site key '<owner>/<suffix>'. */
  prefix: string;
}

/** Does a subtree contain JSX? */
export function containsJsx(input: BaseNode | NodeHolder): boolean {
  let found = false;
  const root = 'node' in input ? input.node : input;
  walkAst(root, {
    enter(node) {
      if (found) return false;
      if (node.type === 'JSXElement' || node.type === 'JSXFragment') {
        found = true;
        return false;
      }
    },
  });
  return found;
}

/** Shared read analysis preserves source identity before transparent lowering. */
export function analyzeMapSite(
  ctx: Ctx, call: MapCallExpression, errorAt: ErrorPath, ownerName: string,
  usedPrefixes: Map<string, number>, parentRow?: ParentRow,
): MapSite {
  const plan = planListSite(captureListSiteInputs(ctx, ownerName), call,
    (message, at) => {throw errorAt.buildCodeFrameError(message, at);},
    parentRow, undefined, ctx.analyzedListSources.get(call));
  if (!ctx.analyzedListSources.has(call)) ctx.analyzedListSources.set(call, {
    key: plan.sourceKey, local: plan.sourceLocal, suffixBase: plan.suffixBase,
  });
  return allocateMapSite(call, plan, ownerName, usedPrefixes);
}

/** Attach occurrence identity and the explicit shared-normalization replacement. */
export function allocateMapSite(
  call: MapCallExpression, plan: ListSitePlan, owner: string, usedPrefixes: Map<string, number>,
): MapSite {
  const {suffixBase, normalizedBody, ...shape} = plan;
  if (normalizedBody !== null) (call.arguments[0] as t.ArrowFunctionExpression).body = normalizedBody;
  const suffix = nextSuffix(suffixBase, usedPrefixes);
  return {...shape, owner, suffix, prefix: `${owner}/${suffix}`};
}

/**
 * Entity-id suffixes generated by other region kinds (`when${n}` for
 * conditionals, `route${n}` for route branches). A list suffix derived from an
 * authored binding such as `let when0` must never claim one of these names:
 * region ids share one namespace per owner.
 */
const RESERVED_REGION_SUFFIX = /^(?:when|route)\d+$/;

function nextSuffix(
  sourceKey: string,
  usedPrefixes: Map<string, number>,
): string {
  let seen = usedPrefixes.get(sourceKey) ?? 0;
  // A source already named like a generated region (`when0`, `route2`) can
  // never escape the reserved pattern by appending digits — `when01` still
  // matches `when\d+` — so derive those from a stem that falls outside it.
  const stem = RESERVED_REGION_SUFFIX.test(sourceKey)
    ? `${sourceKey}x`
    : sourceKey;
  let candidate = seen === 0 ? stem : `${stem}${seen}`;
  // `usedPrefixes` doubles as the set of allocated suffixes: whenever a derived
  // name is claimed (e.g. `items1` for the second `items.map`), it is recorded
  // so a later source literally named `items1` cannot collide with it.
  while (usedPrefixes.has(candidate) || RESERVED_REGION_SUFFIX.test(candidate)) {
    seen += 1;
    candidate = `${stem}${seen}`;
  }
  usedPrefixes.set(sourceKey, seen + 1);
  if (!usedPrefixes.has(candidate)) usedPrefixes.set(candidate, 1);
  return candidate;
}
