/**
 * Transitional type boundary for compiler passes.
 *
 * Runtime AST behavior is fully ESTree-owned. These aliases keep the remaining
 * annotation migration centralized instead of coupling every pass to a parser
 * package. Replace aliases here with `./types` contracts as their shapes are
 * standardized.
 */

export type AstCompatibilityModule = typeof import('@babel/types');

export type {
  ArgumentPlaceholder,
  ArrayExpression,
  ArrayPattern,
  ArrowFunctionExpression,
  AssignmentExpression,
  AssignmentPattern,
  BinaryExpression,
  BlockStatement,
  CallExpression,
  ConditionalExpression,
  Expression,
  File,
  FunctionDeclaration,
  FunctionExpression,
  Identifier,
  IfStatement,
  ImportDeclaration,
  ImportSpecifier,
  JSXAttribute,
  JSXElement,
  JSXExpressionContainer,
  JSXFragment,
  JSXIdentifier,
  JSXMemberExpression,
  JSXNamespacedName,
  JSXOpeningElement,
  JSXSpreadAttribute,
  JSXSpreadChild,
  JSXText,
  LogicalExpression,
  LVal,
  MemberExpression,
  NewExpression,
  Node,
  ObjectExpression,
  ObjectPattern,
  ObjectProperty,
  OptionalCallExpression,
  OptionalMemberExpression,
  PrivateName,
  Program,
  RestElement,
  ReturnStatement,
  SpreadElement,
  Statement,
  Super,
  SwitchCase,
  SwitchStatement,
  TSParameterProperty,
  TSType,
  TSTypeAnnotation,
  TSTypeElement,
  TypeAnnotation,
  UnaryExpression,
  UpdateExpression,
  V8IntrinsicIdentifier,
  VariableDeclaration,
  VariableDeclarator,
} from '@babel/types';
